spring:
  shardingsphere:
    datasource: #数据源
      ds0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: zhaojun98
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/ds_0?characterEncoding=utf-8
        username: root
      ds0slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: zhaojun98
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/ds0slave?characterEncoding=utf-8
        username: root
      ds1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: zhaojun98
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/ds_1?characterEncoding=utf-8
        username: root
      ds1slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: zhaojun98
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/ds1slave?characterEncoding=utf-8
        username: root
      names: ds0,ds0slave,ds1,ds1slave
    sharding:
      master-slave-rules:   # 读写分离
        ds0:
          master-data-source-name: ds0
          slave-data-source-names: ds0slave
        ds1:
          master-data-source-name: ds1
          slave-data-source-names: ds1slave
      tables:
        lou_dong:  #绑定loudong表所在节点
          actual-data-nodes: ds1.loudong

        user: #绑定user表所在节点
          actual-data-nodes: ds0.user
          key-generator:
            column: id
            type: SNOWFLAKE
